export const ACTIVITY_TYPES = {
  CLUB_CREATED: "CLUB_CREATED",
  CLUB_UPDATED: "CLUB_UPDATED",
  CLUB_DELETED: "CLUB_DELETED",
  CLUB_JOINED: "CLUB_JOINED",
  CLUB_LEFT: "CLUB_LEFT",
  CLUB_MEMBERSHIP_REMOVED: "CLUB_MEMBERSHIP_REMOVED",
  CLUB_MEMBERSHIP_APPROVED: "CLUB_MEMBERSHIP_APPROVED",
  CLUB_MEMBERSHIP_UPDATED: "CLUB_MEMBERSHIP_UPDATED",
  USER_CREATED: "USER_CREATED",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
} as const;

export type ActivityType = typeof ACTIVITY_TYPES[keyof typeof ACTIVITY_TYPES];

export const activityTypes = Object.values(ACTIVITY_TYPES);
